# -*- coding: utf-8 -*-
"""president_height.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dh2hsCzMBQItuBT4aMzbUN6rANOmISkf

#US President

The project is a data analysis of the heights of US Presidents. The data is in a CSV file called president_heights.csv and it contains the name, the order in which the person served as president, and their height in centimeters.

## Getting Started
To get started, you need to have the following libraries installed:

  - pandas
  - numpy
  - matplotlib
  - seaborn
"""

#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#filter warnings
import warnings
warnings.filterwarnings('ignore')

#Load data
df = pd.read_csv('https://raw.githubusercontent.com/mutonic/Exploratory_data_analysis/master/president%20height/president_heights.csv')
df.head()

"""### **Data Summary**
This will show the count, mean, standard deviation, minimum, and maximum of the heights.
"""

df['height(cm)'].describe()

"""An other way to do the above summary"""

print('The mean is = ', round(df['height(cm)'].mean(),2))
print('The standard deviation is = ', round(df['height(cm)'].std(), 2))
print('The minimum is = ', round(df['height(cm)'].min(),2))
print('The maximum is = ', round(df['height(cm)'].max(),2))
print('The 25th percentile = ', round(np.percentile(df['height(cm)'], 25),2))
print('The median = ', round(df['height(cm)'].median(), 2))
print('The 75th percentile = ', round(np.percentile(df['height(cm)'], 75),2))

"""### Data Visualization"""

sns.distplot(df['height(cm)'], hist = True, kde = True,bins=10, label='Height distribution of USA President')
plt.title('Height distribution of USA president')
plt.xlabel('height(cm)')
plt.ylabel('Number')
plt.show()

"""### The Shortest and Tallest Presidents"""

# The shortest president
df.loc[df['height(cm)'].idxmin()][1]

#The tallest president
mask = df['height(cm)'] == 193
df.name[mask]

"""## Conclusion
we can conclude that the tallest president was Abraham Lincoln who was 193cm tall, followed by Lyndon B. Johnson who was also 193cm tall. James Madison was the shortest president, with a height of 163cm. To see a complete list of the heights of all US presidents, you can sort the dataframe by height, like this:
"""

df.sort_values(by= 'height(cm)',ascending=False)